### ISSUE TITLE
Unable to Edit/Delete

### ISSUE THREAD

**Issue by WyntherKnight** [jsavko/mouseguard#1]
Unable to edit or delete items under Wise. Unable to delete items under Skills and Traits.

**Comment by jsavko** [comment]
I have confirmed the issue and should have a fix pushed this afternoon

**Comment by jsavko** [comment]
Patch has been pushed. Update the system package and you should be able to delete again.

**Comment by WyntherKnight** [comment]
Thanks! Also, will there be a way that from the character sheet, the Wise, Skill and Trait description/information to be shown on the chat?

**Comment by jsavko** [comment]
As in the descriptions of what they are or their values?

**Comment by WyntherKnight** [comment]
Yes, both of them. Since it's played on a VTT, it will be easier for the information to just be shown on the chat rather than going back to the book and looking for it.

**Comment by jsavko** [comment]
I do not have a license to distribute the copyrighted text of the book. You are welcome to duplicate the compendium and edit it with full text for personal use though.   I'd advise against editing the system compendium though as it will get overwritten during any system updates

**Comment by WyntherKnight** [comment]
I understand, It's not about distributing the info of the book, but rather to have an option or ability to show the information on the Wise, Skill and Traits from the character sheet into the chat area, maybe clicking the name will show it (along with the dice roll) or adding a speech bubble icon next to the item, or right click the name to have a "show to chat" option (along with a "roll dice" option).

**Comment by jsavko** [comment]
The information on the skill, wise, and trait is all copyrighted beside the name.  I can't include that info in the system. Which is why the compendium just has a page number reference.   The actual skill being used in a roll isn't often important since other players helping or choosing to remove dice to hinder yourself for rewards later is the mechanic.  With that said I will look into an option to include the name of what is being rolled

**Comment by WyntherKnight** [comment]
Okay, thanks and again I understand completely about the copyright, But to clarify, you are **NOT** including any copyrighted info in the game whatsoever. Just the **ABILITY** to **SHOW** anything describing the item (wise, skill, talent) in the chat area,

Here's and example on another system., SWADE. The author did not include any copyrighted info form the book, but there is a speech bubble icon then when clicked, will show on the chat area (which is blank). That speech bubble "**option**" is the one I was referring to. 

![image](https://user-images.githubusercontent.com/66346903/148468421-409d50dd-d71e-4680-afee-a70a9ed8c632.png)

I hope this clears it up.
