### ISSUE TITLE
[Feature Request] Add the way to see item description from the character sheet.

### ISSUE THREAD

**Issue by ZwS** [jsavko/mouseguard#14]
It would be nice to have the way to check item description from the character sheet.
I guess there are three was to do so:
1. Add edit button to the items. This will provide ability to open new window where description could be checked. It was mentioned that item editing could be added in #6 . 
2. Put `data-tooltip={item.system.description}` attribute somewhere in item. This will provide tooltip on mouse hover that supports html formatting. This is the easiest option to implement, but I'm not sure if it would work well with large texts, like Armorer or Weather Watcher descriptions.
3. Add foldable description block directly into a character sheet. Seems to be most user friendly option, but I cannot think where it could be placed in the current layout.

**Comment by jsavko** [comment]
Feel free to make a module to achieve the effect you're looking for.  There is no reason for the actor sheet to include skill descriptions that aren't included with the system
