### ISSUE TITLE
How I access the combat tracker?

### ISSUE THREAD

**Issue by AJtheRonin** [jsavko/mouseguard#2]
When trying to make a combat it ask me to chose a Conflict Captain but I can't find where I make that decision.

**Comment by jsavko** [comment]
After adding several tokens to the conflict. Right click the tokens in the combat tracker and select "Toggle Conflict Captain" 
![image](https://user-images.githubusercontent.com/192591/149991969-fa2b4393-0b7b-4821-b519-3a419382a2af.png)

![image](https://user-images.githubusercontent.com/192591/149992009-a6484232-b288-44f7-a174-9aa7e2e85edf.png)
