### ISSUE TITLE
The facing of the 3D dice for "Dice So Nice!" module are wrong.

### ISSUE THREAD

**Issue by LeonxnoeL** [jsavko/mouseguard#20]
The facing of the 3D dice rolled on-screen using "Dice So Nice!" seem to not match the actual die rolled as a result. In fact, the model seems to be lacking the Axe sprite and seems to have too many snakes.

**Comment by jsavko** [comment]
Confirmed when rolling multiple dice the dice faces render wrong. When rolling a single die they render properly

**Comment by LeonxnoeL** [comment]
I still get wrong faces sometimes when rolling a single dice... And the Axe facing seems to be nowhere to be seen.

**Comment by LeonxnoeL** [comment]
Oh crap, I marked it as completed by accident lol. Anyway, I still get wrong facing when rolling single dice. The Axe sprite seems to be nowhere to be seen.

**Comment by jsavko** [comment]
After some investigation we've discovered this is actually a bug within dice so nice!  An update for dice so nice should be released soon to address the issue

**Comment by jsavko** [comment]
The update to dice so nice went out a few minutes ago, and I've confirmed the issue fixed.  Update Dice so nice and things should roll properly again
