### ISSUE TITLE
Tracking Conditions

### ISSUE THREAD

**Issue by Crabe9** [jsavko/mouseguard#21]
I noticed looking through there is nothing on the character sheet for tracking conditions. Even if they don't automatically apply their effects that would be a really great QoL feature for this system as the conditions are very important to play. Thanks for your work on it so far!

**Comment by jsavko** [comment]
This is still on the todo list.  I use status icons to track it on the tokens currently.  

I've a sizable update in the works that includes more control over combat teams, that will include condition tracking as well

**Comment by mdekrey** [comment]
Are you open to contributions? If so, getting that list into Issues would help me get my bearings - I wrote my own Foundry system using many of your same techniques, though I haven't used Svelte. (I wrote mine with TypeScript + React.)

**Comment by jsavko** [comment]
I am open to contributions, but this system is a bit of a mess at the moment.  I was in process of a major combat overhaul and v11 broke some of my work. I just haven't had time to fix everything.  I am hoping to have some time to dedicate to things mid july

**Comment by jsavko** [comment]
I am nearly finished with the next update that includes some major system updates and v11 support.  Here are the icons for tracking conditions 
![image](https://github.com/jsavko/mouseguard/assets/192591/913d083f-c10c-4a22-bb93-54017226f7c6)

Selecting a Token will show you all the status effects for that token as well 
![image](https://github.com/jsavko/mouseguard/assets/192591/a4fe399f-060a-4930-8e0c-5298ff6a690e)

**Comment by jsavko** [comment]
[outputStatus.webm](https://github.com/jsavko/mouseguard/assets/192591/a070e37b-85f1-488e-9196-84c526fcb411)
Video Sample of Status tracking
