### ISSUE TITLE
Is this first or second edition?

### ISSUE THREAD

**Issue by BasiliskOnline** [jsavko/mouseguard#22]
I assumed this was first edition because the Wises aren't correct for second edition, but as I reference the combat cards with 1st and 2nd edition, the combat cards seem to line up more with second edition than first. 

If this is intended to be more in line with second edition (or if its not asking too much, if it is supposed to be first), I'd love to get either an update or option toggle to track wises in conjunction with 2E!

I don't have any real coding experience, outside of minor copying and modifying to get what i want, but ive been poking around the files and I don't even know where I'd find the code used for the wises xD

Thanks so much for all the work either way <3

**Comment by jsavko** [comment]
This is based off 2nd edition
Everything was built out using a physical copy of 2nd edition

**Comment by jsavko** [comment]
Everything was built out using a physical copy of 2nd edition
