### ISSUE TITLE
How does conflict work?

### ISSUE THREAD

**Issue by mdekrey** [jsavko/mouseguard#23]
The  screenshots look beautiful, but I'm unclear on how to set conflict goals and actions for a GM-controlled side (or setting two conflict captains for PVP conflict.) I'm a bit new to running Mouse Guard, but wanted to use your Foundry system!

**Comment by jsavko** [comment]
There is a button to ask the conflict captain for their goal. I am working on an update to stream line the conflict settings currently, but at this time there is no PVP support.  (It is supported in the update that is about 1/2 done) 
  
Once a goal has been set, The captain can distribute the cards to the other actors in the conflict.

**Comment by jsavko** [comment]
I am hoping to have a beta release out today with the option for PVP and drag and drop team setup.  I am finishing up some internal testing.  Here is a preview 

[dragable.webm](https://github.com/jsavko/mouseguard/assets/192591/5199033c-d8b9-42df-95b1-924dd546e941)
