### ISSUE TITLE
Enhancement: Interact with Wises/Skills/Traits

### ISSUE THREAD

**Issue by PointFrankRange** [jsavko/mouseguard#24]
It would be helpful if we click on the name for the Wises, Skills, and traits and it will open up the compendium item for them so we can see any details about those values.

![image](https://github.com/jsavko/mouseguard/assets/68871430/26e3cc64-36f9-4b19-9880-4c42778a654a)

![image](https://github.com/jsavko/mouseguard/assets/68871430/1ca56988-9a3f-489e-8e3e-9f0ebcb69602)

**Comment by jsavko** [comment]
Clicking those labels load the skill into the dice roller

**Comment by PointFrankRange** [comment]
Perhaps the UI could be modified to either have a Dice Icon next to the name for dice rolls and have the skill name open the item details, or keep it the way it is but include a journal Icon next to the name so the details can be presented. Having the means to display what the skill is within the foundry would be a great convenience rather than having to reference the book repeatedly through a session.

**Comment by jsavko** [comment]
You're welcome to make a pull request
