### ISSUE TITLE
Unable to add skills or traits

### ISSUE THREAD

**Issue by Syraxis** [jsavko/mouseguard#3]
When I open the sheet and go to Abilities, wises, skills, and traits, there is only an add item under wises. I dont seem to be able to add skills or traits. 

Thank you!

![image](https://user-images.githubusercontent.com/10501376/180472879-ec60bc53-237b-40a1-9dbd-3c1ab13b3e35.png)

**Comment by jsavko** [comment]
The skills and traits need to be dragged to the sheet from the compendiums

**Comment by Syraxis** [comment]
That got it. Thank you.
