### ISSUE TITLE
Items changes not stored

### ISSUE THREAD

**Issue by ZwS** [jsavko/mouseguard#6]
Once wise added to character sheet it's name does not saved after changing. There is also no way to edit existing wise, clicking on wise title doesn't do anything.

**Comment by jsavko** [comment]
There is currently no way to edit an existing wise.  It's not difficult to add that functionality, so I can look at adding it in the next release

**Comment by ZwS** [comment]
Ok, it seems that changes made to any item not stored regardless of type. I initially thought that this happens only if item is edited from the actor sheet, but this seems to be a global issue.
I've tried to play around this but I don't see a reason why it does not work. No errors produced, changes just silently lost.

**Comment by jsavko** [comment]
What items are you specifically referring to?

**Comment by jsavko** [comment]
I've found the issue.  A fix will be pushed shortly

**Comment by jsavko** [comment]
Fix has been deployed. Thanks for bringing this to attention.
