### ISSUE TITLE
Some strings cannot be translated

### ISSUE THREAD

**Issue by ZwS** [jsavko/mouseguard#7]
There are some strings that cannot be translated:

- Disposition tab: Starting and Current 
- Abilities, Wises, Skills & Traits tab: P and F, Add Item
- character sheet types: character, mouse, weasel, animal

**Comment by jsavko** [comment]
Thanks for the list.  I hadn't finished making the language file, so I will add these items to my workflow

**Comment by jsavko** [comment]
I am also happy to add you translation to the official repo

**Comment by ZwS** [comment]
Thank you for offer. I'm not sure however if the translation will go into your repo. We have separate module that contains translations for all translated modules/systems. It's little bit easier to maintain translations in this way.

**Comment by jsavko** [comment]
> character sheet types: character, mouse, weasel, animal

Item/Actor types can be set with without needing explicit translations using `CONFIG.Actor.typeLabels` 

I have however included them in the translation file for you
